METHOD_NAME: e2e-faster-rcnn-VGG16-C5-10x
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: VGG16.add_VGG16_conv5_body
  NUM_CLASSES: 5
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0005
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 80000
  STEPS: [0, 50000]
RPN:
  SIZES: (128,256,512)
FAST_RCNN:
  ROI_BOX_HEAD: VGG16.add_VGG16_roi_fc_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  WEIGHTS: /home/all/models/Detectron/ImageNetPretrained/vgg16.pkl
  DATASETS: ('caltech_train_10x',)
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 128
  RPN_BATCH_SIZE_PER_IM: 256
TEST:
  DATASETS: ('caltech_test_1x',)
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 300
OUTPUT_DIR: .
